default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: doubtfire_dev
  username: itig
  password: d872$dh
  host:  db
  min_messages: warning

development:
  <<: *default


test:
  <<: *default
  database: doubtfire_dev_test
 

staging:
  adapter:  <%= ENV['DF_STAGING_DB_ADAPTER']  %>
  host:     <%= ENV['DF_STAGING_DB_HOST']     %>
  database: <%= ENV['DF_STAGING_DB_DATABASE'] %>
  username: <%= ENV['DF_STAGING_DB_USERNAME'] %>
  password: <%= ENV['DF_STAGING_DB_PASSWORD'] %>

production:
  adapter:  <%= ENV['DF_PRODUCTION_DB_ADAPTER']  %>
  host:     <%= ENV['DF_PRODUCTION_DB_HOST']     %>
  database: <%= ENV['DF_PRODUCTION_DB_DATABASE'] %>
  username: <%= ENV['DF_PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['DF_PRODUCTION_DB_PASSWORD'] %>
